apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-scheduler
spec:
  replicas: 1
  selector:
    app: kube-scheduler
  template:
    metadata:
      name: kube-scheduler
      labels:
        app: kube-scheduler
    spec:
      serviceAccount: scheduler-account
      containers:
      - name: kube-scheduler
        image: kube-scheduler:latest
        imagePullPolicy: IfNotPresent